name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag test_ci_zhen
    - name: Zip docker image
      run: docker save test_ci_zhen > test_ci_zhen.tar

  build2:

    runs-on: ubuntu-latest

    steps:
    - name: UnZip docker image
      run: docker save -o test_ci_zhen.tar test_ci_zhen