name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag test_ci_zhen:0
    - name: Zip docker image
      run: docker save test_ci_zhen:0 > test_ci_zhen.tar
    - name: Cache packages
      uses: actions/cache/save@v4
      with:
        path: test_ci_zhen.tar
        key : test_ci


  build2:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Restore cached Primes
      uses: actions/cache/restore@v4
      with:
        path: test_ci_zhen.tar
        key: test_ci
    - uses: actions/checkout@v3
    - name: UnZip docker image
      run: docker load --input test_ci_zhen.tar
    - name: Build another image
      run: docker build . --file Dockerfile2 --tag test_ci_zhen2